# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master
  
resources:
  - repo: self
  
variables:
  tag: '$(Build.BuildId)'
  
stages:
  - stage: Build
    displayName: Build image
    jobs:  
    - job: Build
      displayName: Build
      pool: self-hosted
      steps:
      - task: BatchScript@1
        inputs:
          workingFolder: 'samples\dotnetcore\getting-started\mywebapi'
          filename: '"c:\Program Files\Git\usr\bin\dir.exe"'
          arguments: ''      
      - task: BatchScript@1
        inputs:
          workingFolder: 'samples\dotnetcore\getting-started\mywebapi'
          filename: 'c:\Windows\System32\cmd.exe'
          arguments: '/c docker build -t azdz .'