# Docker

# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master
  
resources:
  - repo: self
  
variables:
  tag: '$(Build.BuildId)'
  
stages:
  - stage: Build
    displayName: Build image
    jobs:  
    - job: Build
      displayName: Build
      pool: self-hosted
      steps:
      - task: CmdLine@2
        inputs:
          workingFolder: 'samples\java\getting-started\webfrontend'
          script: |
            docker build -t webfrontend:azdz
            docker login --username kuzhel -p $(dhpswd)
            docker tag webfrontend:azdz kuzhel/webfrontend:azdz
            docker push kuzhel/webfrontend:azdz
          